version: "3.8"

services:
  server:
    build:
      context: ./packages/server
    ports:
      - "4000:4000"
    links:
      - mongo
    environment:
      - DB_URI="mongodb://mongo:27017/moonlook"

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes: /data/db
