version: "3.8"

services:
  nodeserver:
    build:
      context: ./packages/server
    ports:
      - "4000:4000"

  nginx:
    restart: always
    build:
      context: ./packages/nginx
    ports:
      - "81:80"
