//Images
export const GET_IMAGES = "GET_IMAGES";

//Contact
export const SUCCESS_CONTACT = "SUCCESS_CONTACT";
export const ERROR_CONTACT = "ERROR_CONTACT";
export const CLOSE_ERROR_ALERT = "CLOSE_ERROR_ALERT";
export const CLOSE_SUCCESS_ALERT = "CLOSE_SUCCESS_ALERT";
