name: Linter

on:
  push:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          check-latest: true
      - run: yarn install
      - run: yarn run check
